steps:
- script: |
    set -e
    /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
    disown -ar
  displayName: 'Start xvfb'

- script: 'node node_modules/vscode/bin/test'
  displayName: 'Run tests'
  env:
    DISPLAY: :10